#!/bin/bash

# Rhyme Time - Quick Audio Setup Helper

echo "🎵 Rhyme Time - Audio Setup"
echo "================================"
echo ""
echo "The game needs a beat loop MP3 file to work."
echo ""
echo "📥 OPTION 1: Download Free Beat Loop (RECOMMENDED)"
echo "---------------------------------------------------"
echo "1. Visit: https://pixabay.com/music/search/beats/"
echo "2. Search: 'drum loop 120 bpm' or 'metronome'"
echo "3. Download any beat loop MP3 (free, no login needed)"
echo "4. Save it to: $(pwd)/assets/audio/beat-loop-1.mp3"
echo ""
echo "Quick links to free audio:"
echo "  • Pixabay Music: https://pixabay.com/music/"
echo "  • FreeSounds: https://freesound.org/"
echo "  • YouTube Audio Library: https://studio.youtube.com/channel/UC.../music"
echo ""
echo "📁 OPTION 2: Use Any MP3 You Have"
echo "---------------------------------------------------"
echo "For quick testing, ANY MP3 file will work:"
echo ""
echo "# If you have an MP3 file somewhere:"
echo "cp /path/to/your-music.mp3 assets/audio/beat-loop-1.mp3"
echo ""
echo "================================"
echo ""
echo "❓ Need help? Check these files:"
echo "  • assets/audio/README.md - Audio setup guide"
echo "  • QUICKSTART.md - 5-minute setup"
echo "  • SETUP.md - Full setup guide"
echo ""
echo "Once you have the audio file, run:"
echo "  npx expo start"
echo ""
